### PR TITLE
Bring PaperWM in line with extensions.gnome.org rules - preparing for submission

### LINKED ISSUE #322: path name with colon causes problems with gsettings and GSETTINGS_SCHEMA_DIR
this extension uses a `:` (colon) character in its directory name in `~/.local/gnome-shell/extensions`, namely `paperwm@hedning:matrix.org`, which causes problems when using `GSETTINGS_SCHEMA_DIR=...` and the `gsettings` command line tool. the `:` is interpreted as a path separator.

this means `gsettings` cannot be used to configure this extension, as suggested in the readme.

since this is only the extension (out of quite a few on my system) using a non-standard character, i suggest to adhere to the established practices and conventions for gnome extensions, and use an identifier and directory name that do not cause problems.

### LINKED ISSUE #425: install.sh does not automatically enable the extension
install
```
❯ ./install.sh
ln: failed to create symbolic link '/home/ntanghe/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/paperwm@hedning:matrix.org': File exists

PaperWM runs best with some Gnome Shell settings changed:
 workspaces-only-on-primary off: Required for working multi-monitor support
 edge-tiling off: Natively tiled windows doesn't work in PaperWM
 attach-modal-dialogs off: Attached modal dialogs can cause visual glitching

Use recommended settings (generates a backup) [Y/n]: y
restore-gnome-shell-settings-2022-10-13.sh exists

Enable the extension [Y/n]? y
Trying to load and enable extension:
something went wrong:
(false, '')
Success
```

<details><summary>debug</summary>

```
❯ ./debug
Unit gnome-shell-x11.service could not be found.
Unit gnome-shell-wayland.service could not be found.
12:41:00: Running GNOME Shell (using mutter 42.5) as a Wayland display server
12:41:00: Device '/dev/dri/card0' prefers shadow buffer
12:41:00: Added device '/dev/dri/card0' (nvidia-drm) using non-atomic mode setting.
12:41:01: Created gbm renderer for '/dev/dri/card0'
12:41:01: Boot VGA GPU /dev/dri/card0 selected as primary
12:41:01: Disabling DMA buffer screen sharing (implicit modifiers not supported)
12:41:01: Using public X11 display :1024, (using :1025 for managed services)
12:41:01: Using Wayland display name 'wayland-0'
12:41:01: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
12:41:01: Will monitor session c1
12:41:01: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
12:41:01: Extension background-logo@fedorahosted.org already installed in /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org. /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org will not be loaded
12:41:01: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
12:41:01: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
12:41:01: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
12:41:01: Extension appindicatorsupport@rgcjonas.gmail.com already installed in /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com. /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com will not be loaded
12:41:01: Extension gamemode@christian.kellner.me already installed in /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me. /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me will not be loaded
12:41:01: Window manager warning: Failed to parse saved session file: Failed to open file “/var/lib/gdm/.config/mutter/sessions/1031e970c56eb2ff3166565766068130700000025710000.ms”: No such file or directory
12:41:01: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
12:41:02: ATK Bridge is disabled but a11y has already been enabled.
12:41:02: Registering session with GDM
12:41:13: Running GNOME Shell (using mutter 42.5) as a Wayland display server
12:41:13: Device '/dev/dri/card0' prefers shadow buffer
12:41:13: Added device '/dev/dri/card0' (nvidia-drm) using non-atomic mode setting.
12:41:13: Created gbm renderer for '/dev/dri/card0'
12:41:13: Boot VGA GPU /dev/dri/card0 selected as primary
12:41:14: Disabling DMA buffer screen sharing (implicit modifiers not supported)
12:41:14: Using public X11 display :0, (using :1 for managed services)
12:41:14: Using Wayland display name 'wayland-0'
12:41:14: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
12:41:14: Will monitor session 2
12:41:14: Telepathy is not available, chat integration will be disabled.
12:41:14: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
12:41:14: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
12:41:14: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
12:41:14: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
12:41:14: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
12:41:16: GNOME Shell started at Thu Oct 13 2022 12:41:14 GMT+0200 (CEST)
12:41:16: Registering session with GDM
12:43:08: Invalid window geometry for xdg_surface@31. Ignoring for now, but this will result in client termination in the future.
12:43:13: ATK Bridge is disabled but a11y has already been enabled.
12:43:13: Could not create transient scope for PID 5957: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 5957 does not exist.
12:43:13: Could not create transient scope for PID 5965: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 5965 does not exist.
12:47:49: Object .Gjs_ui_workspaceThumbnail_ThumbnailsBox (0x55f8afe82fc0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
12:47:49: == Stack trace for context 0x7f3ea80f54a0 ==
12:47:49: #0   7ffe99708af0 b   resource:///org/gnome/shell/ui/workspacesView.js:639 (18f24e05b8d0 @ 33)
12:47:49: #1   7ffe99708c40 b   resource:///org/gnome/shell/ui/workspacesView.js:686 (18f24e05b970 @ 488)
12:47:49: #2   55f8afbdf4f0 i   resource:///org/gnome/shell/ui/workspace.js:855 (18f24e005c40 @ 370)
12:47:49: #3   55f8afbdf468 i   resource:///org/gnome/shell/ui/workspace.js:806 (18f24e005ba0 @ 17)
12:47:49: #4   55f8afbdf3d0 i   resource:///org/gnome/shell/ui/workspacesView.js:1016 (18f24e05c3d0 @ 124)
12:47:49: #5   55f8afbdf340 i   resource:///org/gnome/shell/ui/overviewControls.js:715 (c903c5bc970 @ 39)
12:47:49: #6   55f8afbdf2b8 i   resource:///org/gnome/shell/ui/layout.js:347 (33ffd1b30470 @ 22)
12:47:49: #7   55f8afbdf228 i   resource:///org/gnome/shell/ui/overview.js:586 (c903c5ba7e0 @ 170)
12:47:49: #8   55f8afbdf1a8 i   resource:///org/gnome/shell/ui/overview.js:564 (c903c5ba790 @ 12)
12:47:49: #9   55f8afbdf128 i   resource:///org/gnome/shell/ui/overviewControls.js:753 (c903c5bcab0 @ 55)
12:47:49: #10   55f8afbdf0a0 i   resource:///org/gnome/shell/ui/environment.js:151 (33ffd1bcc4c0 @ 39)
12:47:49: #11   55f8afbdf018 i   resource:///org/gnome/shell/ui/environment.js:317 (33ffd1bcc9c0 @ 14)
12:47:49: == Stack trace for context 0x7f3ea80f54a0 ==
12:47:49: #0   7ffe99708c40 b   resource:///org/gnome/shell/ui/workspacesView.js:688 (18f24e05b970 @ 505)
12:47:49: #1   55f8afbdf4f0 i   resource:///org/gnome/shell/ui/workspace.js:855 (18f24e005c40 @ 370)
12:47:49: #2   55f8afbdf468 i   resource:///org/gnome/shell/ui/workspace.js:806 (18f24e005ba0 @ 17)
12:47:49: #3   55f8afbdf3d0 i   resource:///org/gnome/shell/ui/workspacesView.js:1016 (18f24e05c3d0 @ 124)
12:47:49: #4   55f8afbdf340 i   resource:///org/gnome/shell/ui/overviewControls.js:715 (c903c5bc970 @ 39)
12:47:49: #5   55f8afbdf2b8 i   resource:///org/gnome/shell/ui/layout.js:347 (33ffd1b30470 @ 22)
12:47:49: #6   55f8afbdf228 i   resource:///org/gnome/shell/ui/overview.js:586 (c903c5ba7e0 @ 170)
12:47:49: #7   55f8afbdf1a8 i   resource:///org/gnome/shell/ui/overview.js:564 (c903c5ba790 @ 12)
12:47:49: #8   55f8afbdf128 i   resource:///org/gnome/shell/ui/overviewControls.js:753 (c903c5bcab0 @ 55)
12:47:49: Object .Gjs_ui_workspaceThumbnail_ThumbnailsBox (0x55f8afe82fc0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
12:47:49: #9   55f8afbdf0a0 i   resource:///org/gnome/shell/ui/environment.js:151 (33ffd1bcc4c0 @ 39)
12:47:49: #10   55f8afbdf018 i   resource:///org/gnome/shell/ui/environment.js:317 (33ffd1bcc9c0 @ 14)
12:47:49:
  JS ERROR: TypeError: windowInfo is undefined
  vfunc_allocate@resource:///org/gnome/shell/ui/workspace.js:706:17
  vfunc_allocate@resource:///org/gnome/shell/ui/workspacesView.js:555:25
  vfunc_allocate@resource:///org/gnome/shell/ui/workspacesView.js:711:30
  removeWindow@resource:///org/gnome/shell/ui/workspace.js:855:29
  addWindow/<.destroyId<@resource:///org/gnome/shell/ui/workspace.js:806:22
  vfunc_hide@resource:///org/gnome/shell/ui/workspacesView.js:1016:38
  vfunc_unmap@resource:///org/gnome/shell/ui/overviewControls.js:715:33
  hideOverview@resource:///org/gnome/shell/ui/layout.js:347:28
  _hideDone@resource:///org/gnome/shell/ui/overview.js:586:32
  _animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:564:55
  onStopped@resource:///org/gnome/shell/ui/overviewControls.js:753:21
  _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
  _easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

12:47:49: Object St.Button (0x55f8b01b0120), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
12:47:49: == Stack trace for context 0x7f3ea80f54a0 ==
12:47:49: #0   55f8b35ffc18 i   resource:///org/gnome/shell/ui/windowPreview.js:566 (18f24e007d80 @ 10)
12:47:49: == Stack trace for context 0x7f3ea80f54a0 ==
12:47:49: #0   55f8b35ffc18 i   resource:///org/gnome/shell/ui/windowPreview.js:567 (18f24e007d80 @ 36)
12:47:49: == Stack trace for context 0x7f3ea80f54a0 ==
12:47:49: #0   55f8b35ffc18 i   resource:///org/gnome/shell/ui/windowPreview.js:570 (18f24e007d80 @ 77)
12:47:49: Object St.Label (0x55f8b11fa450), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
12:47:49: Object .Gjs_ui_windowPreview_WindowPreview (0x55f8b1a0b420), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
12:47:55: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
12:47:55: meta_later_add: assertion 'display' failed
12:47:55: meta_later_remove: assertion 'display' failed
12:47:55: meta_later_remove: assertion 'display' failed
12:47:55: meta_later_add: assertion 'display' failed
12:47:55: meta_later_add: assertion 'display' failed
12:47:55: meta_later_add: assertion 'display' failed
12:47:55: meta_later_add: assertion 'display' failed
12:47:55: meta_later_add: assertion 'display' failed
12:47:55: meta_later_add: assertion 'display' failed
12:47:55: meta_later_add: assertion 'display' failed
12:47:55: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
12:47:55: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
12:47:56: Running GNOME Shell (using mutter 42.5) as a Wayland display server
12:47:56: Device '/dev/dri/card0' prefers shadow buffer
12:47:57: Added device '/dev/dri/card0' (nvidia-drm) using non-atomic mode setting.
12:47:57: Created gbm renderer for '/dev/dri/card0'
12:47:57: Boot VGA GPU /dev/dri/card0 selected as primary
12:47:57: Disabling DMA buffer screen sharing (implicit modifiers not supported)
12:47:57: Using public X11 display :1024, (using :1025 for managed services)
12:47:57: Using Wayland display name 'wayland-0'
12:47:57: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
12:47:57: Will monitor session c2
12:47:57: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
12:47:57: Extension background-logo@fedorahosted.org already installed in /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org. /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org will not be loaded
12:47:57: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
12:47:57: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
12:47:57: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
12:47:57: Extension appindicatorsupport@rgcjonas.gmail.com already installed in /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com. /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com will not be loaded
12:47:57: Extension gamemode@christian.kellner.me already installed in /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me. /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me will not be loaded
12:47:57: Window manager warning: Failed to parse saved session file: Failed to open file “/var/lib/gdm/.config/mutter/sessions/1079000ca6f1951789166565807686157800000070620000.ms”: No such file or directory
12:47:57: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
12:47:58: ATK Bridge is disabled but a11y has already been enabled.
12:47:58: Registering session with GDM
12:47:58: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
12:47:58: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
12:48:11: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
12:48:11: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
12:48:11: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
13:41:16: Running GNOME Shell (using mutter 42.5) as a Wayland display server
13:41:16: Device '/dev/dri/card0' prefers shadow buffer
13:41:16: Added device '/dev/dri/card0' (nvidia-drm) using non-atomic mode setting.
13:41:16: Created gbm renderer for '/dev/dri/card0'
13:41:16: Boot VGA GPU /dev/dri/card0 selected as primary
13:41:16: Disabling DMA buffer screen sharing (implicit modifiers not supported)
13:41:16: Using public X11 display :1024, (using :1025 for managed services)
13:41:16: Using Wayland display name 'wayland-0'
13:41:17: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
13:41:17: Will monitor session c3
13:41:17: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
13:41:17: Extension background-logo@fedorahosted.org already installed in /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org. /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org will not be loaded
13:41:17: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
13:41:17: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
13:41:17: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
13:41:17: Extension appindicatorsupport@rgcjonas.gmail.com already installed in /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com. /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com will not be loaded
13:41:17: Extension gamemode@christian.kellner.me already installed in /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me. /usr/share/gnome-shell/extensions/gamemode@christian.kellner.me will not be loaded
13:41:17: Window manager warning: Failed to parse saved session file: Failed to open file “/var/lib/gdm/.config/mutter/sessions/10b2ce6e337fae3251166566127635070800000147340000.ms”: No such file or directory
13:41:17: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
13:41:17: ATK Bridge is disabled but a11y has already been enabled.
13:41:17: Registering session with GDM
13:41:18: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
13:41:18: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
13:41:32: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
13:41:32: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
13:41:32: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
13:41:32: Running GNOME Shell (using mutter 42.5) as a Wayland display server
13:41:32: Device '/dev/dri/card0' prefers shadow buffer
13:41:32: Added device '/dev/dri/card0' (nvidia-drm) using non-atomic mode setting.
13:41:32: Created gbm renderer for '/dev/dri/card0'
13:41:32: Boot VGA GPU /dev/dri/card0 selected as primary
13:41:33: Disabling DMA buffer screen sharing (implicit modifiers not supported)
13:41:33: Using public X11 display :0, (using :1 for managed services)
13:41:33: Using Wayland display name 'wayland-0'
13:41:33: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
13:41:33: Will monitor session 8
13:41:33: Telepathy is not available, chat integration will be disabled.
13:41:33: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:41:33: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:41:33: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
13:41:34: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:41:34: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:41:35: GNOME Shell started at Thu Oct 13 2022 13:41:33 GMT+0200 (CEST)
13:41:35: Registering session with GDM
13:42:37: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:42:37: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:42:37: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:42:37: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
13:42:37: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
13:42:37: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
13:42:37: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:42:37: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:42:37: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:42:37: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
13:43:39: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5625b0891120] is on because it needs an allocation.
13:43:39: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x5625b1766e60] is on because it needs an allocation.
13:43:39: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x5625b1776ae0] is on because it needs an allocation.
13:43:39: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5625b0891120] is on because it needs an allocation.
13:43:39: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x5625b1766e60] is on because it needs an allocation.
13:43:39: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x5625b1776ae0] is on because it needs an allocation.
13:43:39: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5625b0891120] is on because it needs an allocation.
13:43:39: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x5625b1766e60] is on because it needs an allocation.
13:43:39: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x5625b1776ae0] is on because it needs an allocation.
13:43:39: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5625b0891120] is on because it needs an allocation.
13:43:39: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x5625b1766e60] is on because it needs an allocation.
13:43:39: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x5625b1776ae0] is on because it needs an allocation.
13:43:39: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5625b0891120] is on because it needs an allocation.
13:43:39: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x5625b1766e60] is on because it needs an allocation.
13:43:39: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x5625b1776ae0] is on because it needs an allocation.
13:43:39: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5625b0891120] is on because it needs an allocation.
13:43:39: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x5625b1766e60] is on because it needs an allocation.
13:43:39: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x5625b1776ae0] is on because it needs an allocation.
13:43:39: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5625b0891120] is on because it needs an allocation.
13:43:39: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x5625b1766e60] is on because it needs an allocation.
13:43:39: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x5625b1776ae0] is on because it needs an allocation.
13:43:40: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5625b0891120] is on because it needs an allocation.
13:43:40: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x5625b1766e60] is on because it needs an allocation.
13:43:40: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x5625b1776ae0] is on because it needs an allocation.
13:43:41: Invalid window geometry for xdg_surface@31. Ignoring for now, but this will result in client termination in the future.
```

</details>

### LINKED ISSUE #545: Failed to rebind keybindings using UI
**Describe the bug**
Succeed to rebind `Super + Shift + >` to Switch to the right monitor
Failed to rebind `Super + Shift + <` to Switch to the left monitor

**To Reproduce**
1. Go to Extensions UI settings
2. Click on 'Keybindings'
3. Remove shortcut of 'Move the active window to the left'
4. Scroll down to 'Monitors'
5. Add shortcut for 'Switch to the left monitor'

**Expected behavior**
Shift to left monitor

**Screenshots**
FYI: '右' means right
image

**System information:**
```
Distribution: Fedora Linux
GNOME Shell 44.1
Display server: Wayland
PaperWM branch/tag: v44.1.1
PaperWM commit: 5bf0e3e5387c9f69b795091d66678b6796190772
Enabled extensions:
- paperwm@hedning:matrix.org
- vertical-overview@RensAlthuis.github.com
```

### LINKED ISSUE #558: bug: dragging window to monitor triggers refocus on previous window from that monitor
**Describe the bug**
Often, when I drag a window to a second monitor with my mouse, and select the rightmost location for the window to go, the window will move to the correct location, but then the window to the left will scroll into focus, hiding the new window.

**To Reproduce**
1. Full width app on monitor 2
2. Medium width app on monitor 1
3. Drag app from monitor 1 to 2, and drop it on the right edge of the screen
4. Move the mouse one pixel

**Expected behavior**
The new window is visible on monitor 2.
Instead, the full width app gets focused and centred on monitor 2. 

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Distribution: Fedora Linux
GNOME Shell 44.2
Display server: Wayland
PaperWM branch/tag: develop
PaperWM commit: 249f096e7aa674850bd793b890179125d2d0bf3b
Enabled extensions:
- paperwm@hedning:matrix.org
- cpufreq@konkor
- clipboard-indicator@tudmotu.com
- bluetooth-quick-connect@bjarosze.gmail.com
- espresso@coadmunkee.github.com
- dash-to-panel@jderose9.github.com
- unite@hardpixel.eu
- fullscreen-hot-corner@sorrow.about.alice.pm.me
- Vitals@CoreCoding.com
- notification-timeout@chlumskyvaclav.gmail.com
- appindicatorsupport@rgcjonas.gmail.com
```

**Additional context**
I think this started happening with https://github.com/paperwm/PaperWM/pull/544

### PR DESCRIPTION
**Pull request by jtaala**
Combining #557 with this PR.

This PR (finally) brings PaperWM in line with extensions.gnome.org GJS rules & guidelines, which is necessary for submission of PaperWM to extensions.gnome.org.

See issues #205, #435.

Namely, it:

1. Changes PaperWM to use `enable()` instead of `init()`.  `init()` is executed when loaded (e.g. once when logging in).  From [GJS guide/rules](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#rules):
>
> init() is called by GNOME Shell when your extension is loaded, not when it is enabled. Your extension MUST NOT create any objects, connect any signals, add any main loop sources or modify GNOME Shell here.
>
> It is permitted to create static objects and arrays in the global scope or init() (e.g. enumerations or string lists), but constructing class instances is not permitted. Objects intended to be constructed as instances should be created when enable() is called, and destroyed when disable() is called.

2. renames PaperWM UUID to `paperwm@paperwm.github.com`.  This is needed to avoid several issues related to [#489](https://github.com/paperwm/PaperWM/pull/489) (and also since it needs to be somwhere under the control of PaperWM admins).

3. removes the `metadata.json` version parameter.  This is used by extensions.gnome.org to iterate the version number on new releases.

4. simplifies the `install.sh` script!  Auto enabling has not worked for a long (long) time and just confuses users.  The new install script  now checks if  a non-symlinked PaperWM version exists (e.g. one from extensions.gnome.org... when it's available) and if not, applies the symlink with clear instructions to the user on how to enable it.
   - resolves #425. 

5. an installation from extensions.gnome.org means that users won't need to run the `install.sh` script (yay!)... but that means that the `set-recommended-gnome-shell-settings.sh` script wont' be run as well.  Given this, PaperWM now manages these setttings.  It does this by saving/backing-up (to PaperWM's settings/schema) user's settings for `workspaces-only-on-primary`, `edge-tiling`,  and `attach-modal-dialogs`.  
   - we save these settings to PaperWM's settings for safety (in case gnome terminates before PaperWM can restore etc.)
   - PaperWM will save these settings whenever it is enabled, and restore these setting whenever it is disabled;
   - PaperWM clears the backup'd settings after a successful restore, and will only save them on the next enable if they are clear --> this basically ensures that if gnome terminates (crashes etc.), the user's preferred settings won't be lost.
   - given the above, we've now removed the `set-recommended-gnome-shell-settings.sh`;
   - this simplifies the `install.sh` script.

6. Fixes a lot of issues that were stopping us from a successful submission to extensions.gnome.org:  this includes addressing all issues from the first submission (see #557 for the actual submission issues outlined by the extensions.gnome.org):

- [x] **1 DONE**.   Good pickup and call here - was a bit of a mess.  Including a very interesting hard-coding of the `version` var (was written back before Gnome 40).  In any case, the first commit here was fixing that and removing old/deprecated code that was for gnome 3.xx.
- [x] **2 DONE**.  ~~`sessionModes` removed from metadata.json (not needed in PaperWM).  Also improved the `safeCall` logging to only log if called method exists in module.~~ `unlock-dialog` sessionMode is needed!
   - **Justification:**  PaperWM requires session mode `unlock-dialog` to maintain multi-monitor tiling layouts when locking/unlocking Gnome.  Without this, tiled windows can move to different monitors on gnome unlock (which severely impacts/destroys user workflows).
- [x] **3 DONE**.  I'm not sure of the original reason for setting `Extension` like it was doing.  Replaced with a much simpler `var Extension = imports.misc.extensionUtils.getCurrentExtension();`.
- [x] **4 DONE**.  Removed `convenience.js` as it duplicates current Gnome ExtensionUtils and refactored modules that used it .
- [x] **5 DONE**.  Removed unneeded check.
- [x] **6 DONE.**.  did full review of all `mainloop.timeout_add` instances - most were  actually (intended) as once off calls (e.g. destroy after first handler execution) - changed these to destroy after handler function execution.
- [x] **7 DONE**.  Went through and cleaned up `imports.xxx` references (and moving them to top where possible).
- [x] **8 DONE**. We were actually delegating the animation through `utils.tweener`... which was actually using `Widget.ease(...)`.  This was basically because it was easier to do this when we switched to `ease`.  However, this is quite confusing for users/reviews.  I've taken the opportunity now to rename `Tweener.addTween(...)` to `Ease.addEase(...)` etc.
- [x] **9 DONE** (finally!).  This was a very good point in the review.  Polyfilling in functions on global gnome objects isn't the best approach here.  I've now replaced the polyfills with backwards-compatible utility functions which is a cleaner/safer/better approach and should make this much easier to maintain going forward.
- [x] **10 DONE**.  Replaced the use of `print(...)` across PaperWM. 
- [x] **11 DONE**.  Moved global scope creation of instances to `enable` in `Kludges.sj`, `liveAltTab.js`, `prefs.js`, `tiling.js`.  Also cleaned up  and removed unneeded imports dependencies and improved formatting.
- [x] **12 DONE**. Hmm - we don't see an issue with importing Gtk and using accelerator_parse etc.  But we have cleaned up and removed references to Gtk where not needed.
- [x] **13 DONE**.  We've removed the hot corner overriding/disabling from PaperWM.  This was largely superfluous since hot corner works fine in PaperWM, and if users want to disable it they can do so via the usual gnome setting.  Having two functions that disable hot corner (one in gnome and one in PaperWM) seems superfluous.
- [x] **14 DONE**.  Removed unneeded import in `minimap.js`. 
- [x] **15 DONE**.  `destroy` should not call `dismissDispatcher` since `dismissDispatcher` calls `destroy`... leading to an infinite loop (recursion).
- [x] **16 DONE**.  All `log(...)` lines reviewed and removed superfluous logging; 
- [x] **17 DONE**. Lower-cased PaperWM schema id values and recompiled schema.
- [x] **18 DONE**.  Refactored to  NOT call `setSchemas()` on Settings `init` (is now called on `enable`).
- [x] **19 DONE**.  nulled out vars (that we missed).  Good pickup! 
- [x] **20 DONE**. Now untracking on `destroy()`.
- [x]  **21 DONE**.  Refactored StackOverlay class - added proper destroy method and now removePreview on destroy.
- [x] **22 DONE**. Timeouts are now oneshot (remove/destroy timeout after function callback).
- [x] **23 DONE**.  Added missing semicolons and other cleanup in `virtTiling.js`.
- [x] **24 DONE**. Now using `add_style_class_name` and `remove_style_class_name` to not run over other extension styles.
- [x] **25 DONE**. Removed Gdk import from Tiling.js.
- [x] **26 DONE**.  Removed module self reference from `keybindings.js` and `tiling.js`. 
- [x] **27 DONE**.  Replaced `Gdk.Keymap` (which isn't available in Gnome 40+) with `Clutter.get_default_backend().get_default_seat().get_keymap()` and hence removed `Gdk` import from `keybindings.js`.  Haven't been able to remove `Gtk` since we need `accelerator_parse` from `Gtk`.

### CODE REVIEW

**Comment by Lythenas** [comment]
Is there a meaningful difference between startup and enable? I saw that startup is always(?) just called in enable. If that is the case we should maybe just put all of it in the enable function, or give startup a more meaningful name (or split up the enable functions a bit).

**Comment by jtaala** [comment]
> Is there a meaningful difference between startup and enable? I saw that startup is always(?) just called in enable. If that is the case we should maybe just put all of it in the enable function, or give startup a more meaningful name (or split up the enable functions a bit).

Hey @Lythenas!

No, there's no meaningful difference there - for some of them I just found it easier to rename the original `init` to `startup` and call it in the enable (well, I actually originally called it something like `preenable`).

Including all in enable() would be okay, except in `kludges.js` - that would make `enable` a very large function.  Have any ideas for a more meaningful name?

File: kludges.js [hunk 1]
```diff
@@ -527,7 +331,7 @@ function enable() {
     // Don't hide notifications when there's fullscreen windows in the workspace.
     // Fullscreen windows aren't special in paperWM and might not even be
     // visible, so hiding notifications makes no sense.
-    with (imports.ui.messageTray) {
+    with (MessageTray) {
```
Comment (Lythenas) [inline kludges.js]: Also what does this `with` do? I have never seen that in JS. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with it should be avoided.

File: kludges.js [hunk 2]
```diff
@@ -388,16 +202,22 @@ function restoreMethod(obj, name) {
...
-
 var signals;
-function init() {
-    registerOverridePrototype(imports.ui.messageTray.MessageTray, '_updateState');
+var swipeTrackers;
+var settings;
+var wmSettings;
+function startup() {
+    settings = ExtensionUtils.getSettings();
+    wmSettings = new Gio.Settings({schema_id: 'org.gnome.desktop.wm.preferences'});
```
Comment (Lythenas) [inline kludges.js]: Unfortunately I can't attach a comment to an unchanged line... So here everything in one comment. I would:

- Put all `registerOverridePrototype` calls into `enableOverride` (and maybe rename it to `setupOverrides`.
- Put all the swipe tracker related stuff in a function `setupSwipeTrackers`
- Put these lines in `enable` and also the line `signals = new utils.Signals();`

And we could similarly split up the `enable` function. E.g. into:

- `setupSignals`
- `monkeyPatchWindowManager`
- `monkeyPatchWorkspace`
- `monkeyPatchMessageTray`

(I don't know what modifying the prototype in JS is usually called, but "monkey patching" is often used in Python for similar things)

File: kludges.js (hunk 1 above)
Comment (jtaala) [reply kludges.js]: This is a good question!  I'm not sure - I just changed the imports reference.  Let's look at changing it.

Comment (jtaala) [reply kludges.js]: So! turns out this monkey patching of MessageTray is actually not needed at all (should have testing just removing this for #553).  That is, default gnome behaviour now actually does what #553 was doing by modifying the monkey patch!

Removed it entirely.  Problem solved!

File: kludges.js (hunk 2 above)
Comment (jtaala) [reply kludges.js]: Hey @Lythenas!  I've implemented these (check the latest).  Simplified quite a bit and implemented the override functions into one place.

Also removed MessageTray as not needed/used now.

Cheers!

**Comment by jtaala** [comment]
@Lythenas!

I'm keen on getting this merged in.  It's a big one though, and has lots of changes, improvements, and bugfixes.  It's a hell of alot cleaner, meaner, and does things in a much more gnome "friendly" way.

I've been testing it solidly this past week (and as I've been developing this PR).

Of note, please see point 4 & 5:

> 4. simplifies the `install.sh` script!  Auto enabling has not worked for a long (long) time and just confuses users.  The new install script  now checks if  a non-symlinked PaperWM version exists (e.g. one from extensions.gnome.org... when it's available) and if not, applies the symlink with clear instructions to the user on how to enable it.
> 
> 5. an installation from extensions.gnome.org means that users won't need to run the `install.sh` script (yay!)... but that means that the `set-recommended-gnome-shell-settings.sh` script wont' be run as well.  Given this, PaperWM now manages these setttings.  It does this by saving/backing-up (to PaperWM's settings/schema) user's settings for `workspaces-only-on-primary`, `edge-tiling`,  and `attach-modal-dialogs`.  
>    - we save these settings to PaperWM's settings for safety (in case gnome terminates before PaperWM can restore etc.)
>    - PaperWM will save these settings whenever it is enabled, and restore these setting whenever it is disabled;
>    - PaperWM clears the backup'd settings after a successful restore, and will only save them on the next enable if they are clear --> this basically ensures that if gnome terminates (crashes etc.), the user's preferred settings won't be lost.
>    - given the above, we've now removed the `set-recommended-gnome-shell-settings.sh`;
>    - this simplifies the `install.sh` script.

**Comment by Lythenas** [comment]
@jtaala I ran into the first error. After installing and enabling it for the first time:

```
PaperWM
Error occured in user @enable:

Tiling is undefined

enable@/home/ms/.config/paperwm/user.js:29:5
safeCall@/home/ms/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:61:52
run@/home/ms/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:49:17
enable@/home/ms/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:97:12
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:196:38
async*_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:552:24
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:627:18
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:223:29
EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:447:38
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
```

It still works fine on my first monitor but PaperWM on my second monitor is broken. (Gnome 44.2 if that matters)

The same error also reappears after locking and unlocking.

After logging out completely and logging back in the error still appears but it seems like the second monitor also works correctly now.

Note that I did a complete fresh install, removed old symlink, made a new clone, checked out and ran the install script.

**Comment by jtaala** [comment]
> @jtaala I ran into the first error. After installing and enabling it for the first time:

Thanks @Lythenas. 

That error is actually from your `user.js` (user defined code) in your `home/ms/.config/paperwm/user.js` - looks like you have some custom code in there (it's not the standard tempate `user.js` that PaperWM installs).

Can you post your `user.js` content?

A couple of options - you can fix (or delete) line 29 in user.js - or a better option, is I'll wrap the user.js `init` and `enable` calls in try/catch, since we can't know/control what users do there (but at least can try harden PaperWM against user defined init/enable issues and print them to log).

**Comment by jtaala** [comment]
Oh, actually it's already wrapped so that error is just a log output saying that there's an issue in the users own `user.js`.

I'm interested though in the second monitor PaperWM being broken though.  Can you elaborate there?  I'll do some more second monitor testing.

**Comment by jtaala** [comment]
> The same error also reappears after locking and unlocking.
> 
> After logging out completely and logging back in the error still appears but it seems like the second monitor also works correctly now.
> 
> Note that I did a complete fresh install, removed old symlink, made a new clone, checked out and ran the install script.

Okay, just checking, on first install (of this branch) did you logout/login and the second monitor PaperWM wasn't working right?  Or were you on X11 and just did a `alt+f2` `r`?  After your login/logout are you still seeing funniness?  can you try reproduce that?

I'm running second monitor now, haven't seen anything yet (apart from the focus mode icon being placed funny after and lock/unlock, until you move your mouse to that monitor and it corrects itself - I'll fix that though).

Oh, and def post your `user.js` - we can then see what the issue is - if it's doing nothing useful then you can just blow it away to get rid of that error notification in the logs.

**Comment by jtaala** [comment]
@Lythenas, all, please pull the latest here - I've restored session mode `unlock-dialog` in metadata.json.

> - [x] **2 DONE**.  ~~`sessionModes` removed from metadata.json (not needed in PaperWM).  Also improved the `safeCall` logging to only log if called method exists in module.~~ `unlock-dialog` sessionMode is needed!
>   - **Justification:**  PaperWM requires session mode `unlock-dialog` to maintain multi-monitor tiling layouts when locking/unlocking Gnome.  Without this, tiled windows can move to different monitors on Gnome unlock (which severely impacts user workflows).

**Comment by jtaala** [comment]
@Lythenas, scrap that - found it.  So, since PaperWM doesn't run stuff in `init` anymore, it wasn't calling `user.js`'s `init` method - that's why you `user.js` (which has some stuff in `enable` that relies on `init` being run) fell over.

I'll fix this up, so any previous `user.js` code runs as before.

**Comment by Lythenas** [comment]
Also on gnome 42.5 I run into this:

```
-En PaperWM
Error occured in tiling @enable:

global.compositor is undefined

later_add@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/utils.js:549:9
updateMonitor@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/topbar.js:777:15
finish@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1698:20
monitorsChanged@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1778:9
Spaces@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1604:14
enable@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:2723:14
safeCall@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:62:52
run@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:45:14
enable@/home/mase271683/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:107:12
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:183:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:532:35
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:532:14
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:533:46
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:210:29
EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:448:38
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:310:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34

```

**Comment by jtaala** [comment]
> Also on gnome 42.5 I run into this:
> 
> ```
> -En PaperWM
> Error occured in tiling @enable:
> 
> global.compositor is undefined
> ```

Thanks @Lythenas.  Fixed!

**Comment by Lythenas** [comment]
> @Lythenas, scrap that - found it. So, since PaperWM doesn't run stuff in `init` anymore, it wasn't calling `user.js`'s `init` method - that's why you `user.js` (which has some stuff in `enable` that relies on `init` being run) fell over.
> 
> I'll fix this up, so any previous `user.js` code runs as before.

Ah, sorry I didn't realize the error was in my user.js, sorry. But the error is fixed with you latest changes, thanks.

For the record, I think my user.js is just the template one with some `Tiling.defwinprop`s from before it was configurable in the settings UI.

I will try your other fixes on gnome 42 tomorrow.

**Comment by Lythenas** [comment]
Also should we maybe update the `user.js` template to not use `init`? But I would prefer to still support calling it to not break other users (although I don't know how many really have much code there, since it is a pain to edit this on wayland).

**Comment by jtaala** [comment]
> Also should we maybe update the `user.js` template to not use `init`? But I would prefer to still support calling it to not break other users (although I don't know how many really have much code there, since it is a pain to edit this on wayland).

Yep, already have.  Using `init` is still valid for several use cases, so I think it's fine for `user.js` template - it's just that PaperWM modules don't need/rely on `init` anymore (and there's some advantages to doing so).  The template is also now simplified and cleaned up, with some modules already defined at top level.

For example, you can now reload `user.css` styles by disabling/enable PaperWM (without needing to restart).  I updated the README.md re this.  Actually, I'll re-add the `Main.loadTheme()` method reference in README.md (since that's still valid).

**Comment by Lythenas** [comment]
Tested on Gnome 42 today and it also seems to work fine.

File: README.md [hunk 3]
```diff
@@ -25,18 +28,16 @@ Clone the repo and check out the branch supporting the Gnome Shell version you'r
...
 from the repository. The installer will create a link to the repo in
-`$XDG_DATA_HOME/gnome-shell/extensions/`. It will then ask if you want to apply
-the recommended settings (see [Recommended
-Settings](#recommended-gnome-shell-settings)) and lastly it will ask to enable PaperWM.
+`$XDG_DATA_HOME/gnome-shell/extensions/`. It will then ask if you want to enable PaperWM.
 ```bash
 ./install.sh # install, load and enable paperwm
 ```
-> ⚠️ You will likely need to restart Gnome shell after installing PaperWM, e.g. logout then login, or restart in place with an `alt-F2` and entering `r` (X11 only).
+> #### ➡️ You may need to restart Gnome shell after installing PaperWM, e.g. logout then login, or restart in place with an `alt-F2` and entering `r` (X11 only).
```
Comment (Lythenas) [inline README.md]:
```suggestion
> #### ➡️ You will need to restart Gnome shell after installing PaperWM, e.g. logout then login, or restart in place with an `alt-F2` and entering `r` (X11 only).
```

I feel like this would be better because wayland is now more or less the default.

File: README.md [hunk 4]
```diff
@@ -25,18 +28,16 @@ Clone the repo and check out the branch supporting the Gnome Shell version you'r
 
 Then run the [`install.sh`](https://github.com/paperwm/PaperWM/blob/release/install.sh) script
 from the repository. The installer will create a link to the repo in
-`$XDG_DATA_HOME/gnome-shell/extensions/`. It will then ask if you want to apply
-the recommended settings (see [Recommended
-Settings](#recommended-gnome-shell-settings)) and lastly it will ask to enable PaperWM.
+`$XDG_DATA_HOME/gnome-shell/extensions/`. It will then ask if you want to enable PaperWM.
```
Comment (Lythenas) [inline README.md]:
```suggestion
`$XDG_DATA_HOME/gnome-shell/extensions/` (usually in `~/.local/share/gnome-shell-extension/`). It will then ask if you want to enable PaperWM.
```

or simply directly write the path instead of `$XDG_DATA_HOME`

File: config/user.js [hunk 5]
```diff
@@ -0,0 +1,16 @@
+// -*- mode: gnome-shell -*-
+var Extension = imports.misc.extensionUtils.getCurrentExtension();
+var Tiling = Extension.imports.tiling;
+var Keybindings = Extension.imports.keybindings;
+
+function init() {
+    // Runs _only_ once on Gnome login (or Gnome shell restart)
+}
```
Comment (Lythenas) [inline config/user.js]: Should we maybe just remove this from the template, since it is not recommended to be used anyway?

If you want to keep it we should at least make it clear that all code should usually be in `enable`.

File: extension.js [hunk 6]
```diff
@@ -77,31 +78,17 @@ var SESSIONID = ""+(new Date().getTime());
...
  * cycles. So we need to keep track of whether we're initialized..
  */
-var initRun = false;
 var enabled = false;
 let lastDisabledTime = 0; // init (epoch ms)
 
-var Extension, convenience;
+/**
+ * Runs once on extension init().
+ * Not run on PaperWM modules, but if a user as a `user.js` module defined
```
Comment (Lythenas) [inline extension.js]:
```suggestion
 * Not run on PaperWM modules, but if a user has a `user.js` module defined
```

File: extension.js [hunk 7]
```diff
@@ -111,8 +98,16 @@ function enable() {
         return;
     }
 
-    if (run('enable'))
+    SESSIONID += "#";
+    Extension = imports.misc.extensionUtils.getCurrentExtension();
+    warnAboutGnomeShellVersionCompatibility();
```
Comment (Lythenas) [inline extension.js]: Since we are now calling this on every enable, it might "spam" the user a bit with warnings. We should add a check to only run it once.

File: generate-extension-zip.sh [hunk 8]
```diff
@@ -0,0 +1,14 @@
+#!/bin/sh
+
+# Creates a zip of (only) the necessary files required by Gnome for the PaperWM extension.
+# Designed for submitting a zip to extensions.gnome.org.
+/usr/bin/zip -r paperwm@paperwm.github.com.zip \
```
Comment (Lythenas) [inline generate-extension-zip.sh]:
```suggestion
zip -r paperwm@paperwm.github.com.zip \
```

Why are you using an absolute path?

File: install.sh [hunk 9]
```diff
@@ -1,85 +1,36 @@
...
-    # String is already quoted and escaped; we want to print the unescaped version
-    unescaped="$(echo "$RET" | sed -e "s/(true, '\"//" | sed -e "s/\\\\n/\n/g")"
+If this is the first time installing PaperWM, then please logout/login 
+and enable the PaperWM extension, either with the Gnome Extensions application, 
+or manually by executing the following command from a terminal:
 
-    echo "Could not enable PaperWM automatically. You may need to enable it manually."
-    printf 'Debug output: %s\n' "$unescaped"
-fi
+/usr/bin/gnome-extensions enable ${UUID}
```
Comment (Lythenas) [inline install.sh]:
```suggestion
gnome-extensions enable ${UUID}
```

File: keybindings.js [hunk 10]
```diff
@@ -1,51 +1,47 @@
...
 var Navigator = Extension.imports.navigator;
 var Tiling = Extension.imports.tiling;
+var LiveAltTab = Extension.imports.liveAltTab;
+var Scratch = Extension.imports.scratch;
+var App = Extension.imports.app;
 
 var display = global.display;
 
-var KEYBINDINGS_KEY = 'org.gnome.Shell.Extensions.PaperWM.Keybindings';
+var KEYBINDINGS_KEY = 'org.gnome.shell.extensions.paperwm.keybindings';
```
Comment (Lythenas) [inline keybindings.js:24]: Can we actually use this constant string in the functions below?

File: keybindings.js [hunk 11]
```diff
@@ -254,23 +242,10 @@ function byId(mutterId) {
...
-} else {
-    asKeyHandler = (actionHandler) =>
-        (display, mw, binding) => {
-            return actionHandler(mw, Tiling.spaces.selectedSpace, {display, binding});
-        };
-}
+var asKeyHandler = (actionHandler) =>
+    (display, mw, binding) => {
+        return actionHandler(mw, Tiling.spaces.selectedSpace, { display, binding });
+    };
```
Comment (Lythenas) [inline keybindings.js]: I think there is no point keeping this an arrow function since it is on the global scope anyway.

File: tiling.js [hunk 12]
```diff
@@ -1325,13 +1281,26 @@ border-radius: ${borderWidth}px;
         }
     }
 
+    /**
+ * Updates workspace topbar icon positions.
+ */
```
Comment (Lythenas) [inline tiling.js]:
```suggestion
    /**
     * Updates workspace topbar icon positions.
     */
```

File: utils.js [hunk 13]
```diff
@@ -448,26 +429,31 @@ var Signals = class Signals extends Map {
...
     }
-}
+};
 
-var tweener = {
-    addTween(actor, params) {
+/**
+ * Note the name `Tweener` used previously was just a legacy name, we're actually using
+ * Widget.ease here.  This was renamed to avoid confusion with the deprecated `Tweener`
+ * moddule.
```
Comment (Lythenas) [inline utils.js]:
```suggestion
 * module.
```

**Review by Lythenas — CHANGES_REQUESTED** [review]
I took some time to try to review this more thoroughly. But it is possible I still missed something. Github (or git) sometimes does not display the diff that great.

Most of the things I found are just nitpicks. So after fixing them I'm fine with approving this.

File: config/user.js (hunk 5 above)
Comment (jtaala) [reply config/user.js]: @Lythenas - yeah, I'm starting to think this too.  Even more, [the latest review by extensions.gnome.org](https://extensions.gnome.org/review/43111) want use to remove that init() entirely  - so `user.js` init wouldn't be called.

Now, if they have code in user.js init(), it won't break PaperWM but it will give an error notification to the user.  I'm not sure how many use that, but it would require moving to enable/disable (which is better here anyways).

We could remove the above init(), and maybe use the template with some comments re that.

File: extension.js (hunk 7 above)
Comment (jtaala) [reply extension.js:103]: Oh good point - yeah, we should actually use in functions!

File: keybindings.js (hunk 10 above)
Comment (jtaala) [reply keybindings.js:24]: Oh good point - yeah, we should actually use in functions!

File: config/user.js (hunk 5 above)
Comment (Lythenas) [reply config/user.js]: Unfortunately I also can't tell you how many people even have code in `user.js`.

Maybe to (kind of) retain the old behavior, we could call the init of `user.js` on the very first call of `enable` (right before `enable` of the `user.js`). I expect this wouldn't break anything for the user.

Also I think it would also be reasonable for use to just remove the support for `user.js` entirely. It is not actually that much less code than creating a second extension (basically just the `metadata.json` is missing). In that second extension we (or users) would not be restricted by gnome guidelines. (We can of course still provide a template for that and/or a script to create that second extension)

File: utils.js (hunk 13 above)
Comment (jtaala) [reply utils.js]: ~~@Lythenas - I like these changes.  Can you please do a PR (into this PR) with your suggested changes?~~

~~Will make it much easier for me.~~

Comment (jtaala) [reply utils.js]: @Lythenas  - I've added most of these changes.  Can talk re the other points.

File: extension.js (hunk 7 above)
Comment (jtaala) [reply extension.js]: Yes, I think so.  The other option is remove this check / warning entirely.  `metadata.json` now is stricter in versions supported, e.g. if it's not running `42`, `43`, or `44` you won't be able enable this extension.

The only advantage I can see with keeping this is if we enable early/prelim support for `45` - although, lessons from `44` issues suggest we should just do that in a `45` branch for users that are on `45` to test etc.

I'm thinking we don't need this anymore - thoughts?

File: config/user.js (hunk 5 above)
Comment (jtaala) [reply config/user.js]: So, I pushed some changes to:

- remvoe `init()` from user.js template;
- remove `init()` from extensions.js;
- run user.js `init` on first PaperWM enable;
- also only run `warnAboutGnomeShellVersionCompatibility` on first enable.

File: extension.js (hunk 7 above)
Comment (jtaala) [reply extension.js]: So, I pushed some changes to: only run `warnAboutGnomeShellVersionCompatibility` on first enable (and not subsequent enable/disable calls).

Did this as an interim until we decide if we want to keep this check (or if you can think of other use/corner cases where this check woudl be needed).

Comment (Lythenas) [reply extension.js]: Yes, I think now with the new `release` branch we can also remove this warning. Because now people will not as easily accidentally update paperwm to an experimental state.
