### PR TITLE
FIX and improve new window create/insert tween (animation)

### LINKED ISSUE #328: Visual artifacts when opening windows with mutter 3.36.4
3.36.3 (good)

3.36.4 (bad, notice the blue rectangles)

I bisected the mutter commit that introduced this down to https://gitlab.gnome.org/GNOME/mutter/-/commit/44a3358125317dbe2151cf0ac70ec2c382236881.

I can only reproduce this using PaperWM, vanilla GNOME doesn't seem to be affected.

### PR DESCRIPTION
**Pull request by jtaala**
Fixes #328.

This PR fixes and improves the new window create/insert tween.  Also resolves a noticable issue where part of current selected window is clipped during window creation.

See below for comparison between current tween and new tween:

**Note the transitions have been slowed down for demonstration purposes.  Also, I'm using a styled `selection` (pinkish colour - because I like it but also to see it better for this demonstration)**

### current transitions (slowed down so can see issues with certain applications):
https://user-images.githubusercontent.com/30424662/228228961-34250abe-7fb6-4141-a1c7-a55f23b54ec4.mp4

### new (improved) transitions (slowed down to see them better):
https://user-images.githubusercontent.com/30424662/228229082-d0088765-6cd8-499f-8c06-26dfba21952e.mp4

_NOTE: this PR has been implemented in the [PaperWM-redux](https://github.com/PaperWM-redux/PaperWM) fork, which you can install if you want this, or any of [my PRs](https://github.com/paperwm/PaperWM/pulls/jtaala) that are open._

### CODE REVIEW

**Comment by paradajz** [comment]
Does this also fixes https://github.com/paperwm/PaperWM/issues/347?

File: tiling.js [hunk 1]
```diff
@@ -2911,16 +2919,19 @@ function insertWindow(metaWindow, {existing}) {
 
     if (!existing) {
         actor.opacity = 0;
+        actor.visible = false;
         clone.x = clone.targetX;
         clone.y = clone.targetY;
-        clone.set_scale(0, 0);
+        clone.set_scale(0, 1);
```
Comment (Lythenas) [inline tiling.js:2925]: I don't particularly care. But do we want to change this? It seems the graphical artifacts are just because of the selection background. Or am I misunderstanding something?

**Review by Lythenas — COMMENTED** [review]
This seems fine to me. But I will test it tomorrow.

File: tiling.js (hunk 1 above)
Comment (jtaala) [reply tiling.js:2925]: I vote yes!  That was part of the "improves".  I think it looks much much better / smoother (especially with faster `animation-time` parameters).  Plus, it just looks cooler (IMHO) when you (for example) drag a browser tab (e.g. to make it into a new window) and it just expands naturally to the right.  Happy to hear contrary opinions though!

Might be a small change/improvement but [scout's rule!](https://auth0.com/blog/a-scout-approach-to-software-development/).

**Comment by jtaala** [comment]
> Does this also fixes #347?

Not intentionally.  I had a quick look at that one and couldn't quite understand from the video what glitch they were referring to (was it the pdf viewer in the video that looked weird?).

If so, I haven't experienced that issue (i.e. I can't reproduce).  I'll comment on that issue directly.

File: tiling.js (hunk 1 above)
Comment (Lythenas) [reply tiling.js:2925]: With this we stretch the window is just one dimension and I think then I notice the stretching more in the text. But I think it is probably fine since most of the time I am only scrolling left to right this makes it a bit more consistent.

**Review by Lythenas — APPROVED** [review]
