### PR TITLE
fix: gnome crash when opening a new window while a window on the scratch layer is selected

### LINKED ISSUE #427: Zoom modal scratch window causes PaperWM, gnome-shell crash (libmutter involved?)
Running into this issue after a Zoom call ends with the "Host has ended the meeting" modal. When the post-call Zoom modal opens, I get a crash that seems to cause PaperWM to crash and restart.

## Steps to reproduce

- Start a Zoom call on another device
- Join the Zoom call from the device running PaperWM
- Terminate the Zoom call from the other device

## Expected behavior

The "Host has ended the meeting" modal appears, and PaperWM does not crash

## Actual behavior

When the "Host has ended the meeting" modal appears, it has no window controls. PaperWM seems to crash and restart soon after.

## Error messages from `journalctl $(which gnome-shell)`

```
Oct 14 12:14:51 monolith gnome-shell[68048]: WARNING: window already registered Zoom
Oct 14 12:14:51 monolith gnome-shell[68048]: WARNING: window already registered Zoom
Oct 14 12:14:51 monolith gnome-shell[68048]: JS ERROR: undefined
                                              registerWindow@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2273:15
                                             window_created@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2214:14
Oct 14 12:14:51 monolith gnome-shell[68048]: JS ERROR: undefined
                                              registerWindow@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2273:15
                                             window_created@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2214:14
Oct 14 12:14:51 monolith gnome-shell[68048]: WARNING: window already registered Zoom
Oct 14 12:14:51 monolith gnome-shell[68048]: JS ERROR: undefined
                                              registerWindow@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2273:15
                                             window_created@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2214:14
Oct 14 12:14:51 monolith gnome-shell[68048]: WARNING: window already registered Zoom
Oct 14 12:14:51 monolith gnome-shell[68048]: JS ERROR: undefined
                                              registerWindow@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2273:15
                                             window_created@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2214:14
Oct 14 12:14:51 monolith gnome-shell[68048]: WARNING: window already registered Zoom
Oct 14 12:14:51 monolith gnome-shell[68048]: JS ERROR: undefined
                                              registerWindow@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2273:15
                                             window_created@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2214:14
Oct 14 12:14:51 monolith gnome-shell[68048]: WARNING: window already registered Zoom
Oct 14 12:14:51 monolith gnome-shell[68048]: JS ERROR: undefined
                                              registerWindow@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2273:15
                                             window_created@/home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2214:14
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5629937345d0] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <unnamed>[<MetaBackgroundGroup>:0x562993734f60] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <spaceContainer>[<ClutterActor>:0x562998ec1900] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <clip>[<ClutterActor>:0x5629b6721150] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <space-actor>[<ClutterActor>:0x5629b6720e20] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <clone-clip>[<ClutterActor>:0x5629b6720af0] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <clone-container>[<StWidget>:0x562996315580] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <unnamed>[<ClutterActor>:0x562996829e50] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <unnamed>[<ClutterClone>:0x5629add78e80] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x562998be1760] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x562993b350d0] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <minimap-background>[<StWidget>:0x5629b389b1c0] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <container-clip>[<StWidget>:0x562996004230] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <minimap-container>[<StWidget>:0x5629bf6c5500] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <window-clone-container>[<ClutterActor>:0x5629990551b0] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: Can't update stage views actor <unnamed>[<ClutterClone>:0x5629a5e2bf80] is on because it needs an allocation.
Oct 14 12:14:51 monolith gnome-shell[68048]: **
Oct 14 12:14:51 monolith gnome-shell[68048]: libmutter:ERROR:../src/compositor/compositor.c:611:invalidate_top_window_actor_for_views: assertion failed: (!priv->frame_in_progress)
Oct 14 12:14:51 monolith gnome-shell[68048]: Bail out! libmutter:ERROR:../src/compositor/compositor.c:611:invalidate_top_window_actor_for_views: assertion failed: (!priv->frame_in_progress)
Oct 14 12:14:51 monolith gnome-shell[68048]: == Stack trace for context 0x562993044170 ==
Oct 14 12:14:51 monolith gnome-shell[68048]: #0   56299321cc90 i   resource:///org/gnome/shell/ui/main.js:737 (1aa8539bfa10 @ 243)
Oct 14 12:14:51 monolith gnome-shell[68048]: #1   56299321cb70 i   /home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2539 (33826aae4c0 @ 670)
Oct 14 12:14:51 monolith gnome-shell[68048]: #2   56299321cad8 i   /home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2249 (33826aae060 @ 45)
Oct 14 12:14:51 monolith gnome-shell[68048]: #3   56299321ca28 i   /home/derrick/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/utils.js:426 (33826ab2790 @ 160)
Oct 14 12:14:52 monolith gnome-shell[433484]: Running GNOME Shell (using mutter 43.0) as a X11 window and compositing manager
Oct 14 12:14:52 monolith gnome-shell[433484]: ATK Bridge is disabled but a11y has already been enabled.
Oct 14 12:14:52 monolith gnome-shell[433484]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
Oct 14 12:14:52 monolith gnome-shell[433484]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
Oct 14 12:14:52 monolith gnome-shell[433484]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Oct 14 12:14:52 monolith gnome-shell[433484]: Will monitor session 2
```

## Environment

- `Linux monolith 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64 GNU/Linux
`
- Gnome Shell 43.0
- PaperWM at commit https://github.com/paperwm/PaperWM/commit/3bedb67f22881343c7b66639d28732fa6493d894

### LINKED ISSUE #448: Opening a new window while a window on the scratch layer is selected crashes gnome
## Summary
Opening a new window, while a window on the scratch layer is selected immediately crashes gnome.  

Am on the latest Manjaro and **Gnome 43.1**.

## Steps to reproduce
1. send a window (e.g. a browser window) to the scratch layer;
2. select (if not already selected) the scratchlayer window;
3. open a new window - for example with Ctrl+N, or open gnome overview and click an app on the dash);
4. gnome crashes...

## Expected behaviour
Gnome not crashing.

## Notes:
1. happens in wayland and x11;
2. happens on Gnome 43.1 (only one I've tested);
3. also happens when the only extension enabled is PaperWM - so happens with or without other extensions being enabled.

### PR DESCRIPTION
**Pull request by jtaala**
FIXES #448 
Looks like it also FIXES #427 

Fix for potential mutter change/regression (currently seeing in GNOME 43.1+) when opening a new application while a window in the scratch layer is selected causes a gnome to crash.

See https://github.com/pop-os/shell/issues/1550 for similar issue currently seen in pop-shell extension.

### CODE REVIEW

**Comment by jtaala** [comment]
Note, if this is caused by a recent regression/change in mutter (which is what I believe atm) - then this change might not be needed if/when mutter fixes whatever is causing this.

**Comment by hallettj** [comment]
I can confirm that this fixes the described crash for me. For quite a while I have been able to consistently crash my Gnome session by putting Slack into the scratch layer, and invoking either the "Upload from your computer" or "Create a post" features. (Both of those attempt to open a new window.) The fix is much appreciated!

**Comment by scottames** [comment]
> I can confirm that this fixes the described crash for me. For quite a while I have been able to consistently crash my Gnome session by putting Slack into the scratch layer, and invoking either the "Upload from your computer" or "Create a post" features. (Both of those attempt to open a new window.) The fix is much appreciated!

Same here. _Very_ much appreciated!

**Review by hallettj — APPROVED** [review]

**Comment by paradajz** [comment]
Tried it out on my PC. It fixes this issue indeed.

**Comment by jtaala** [comment]
Morning all! @Gelbana @tadfisher @ccope - was speaking with @smichel17 and he mentioned to ping you for code reviews.  Hope eveyone has had a good break (or at least a break from work etc.).

If needed (noting that @hallettj approved this PR previously) when someone has time, could I get you to review this PR?  Fixes an easily reproducible bug that's in Gnome 43 (and likely earlier 40+ versions).

File: tiling.js [hunk 1]
```diff
@@ -2536,7 +2536,15 @@ function insertWindow(metaWindow, {existing}) {
...
-                Main.activateWindow(metaWindow);
+                /**
+                 * fix for potential mutter change/regression (currently seeing in
+                 * GNOME 43.1.  See https://github.com/paperwm/PaperWM/issues/448).
+                 * Now using "transitions-completed" signal before
+                 * activating new window on scratch layer.
+                 */
+                signals.connectOneShot(actor,'transitions-completed', () => {
+                    Main.activateWindow(metaWindow);
+                });
```
Comment (smichel17) [inline tiling.js]: Is this the kind of bug that might pop up again in other places? Does it make sense to pull this out into a helper function, or is it not really re-usable? My main concern is how the accumulation of workarounds like this might make this function hard to understand or change. In other words, where is the right place for this complexity to live?

I have no knowledge of gnome-shell internals and very little of PaperWM, so these are actual questions, not opinions-disguised-as-questions. If this is the right place, that's good; I only want to make sure it was considered.

Comment (jtaala) [reply tiling.js]: This is a really good question - as far as I can tell, the error/issue is only observed with floating windows and not those managed while tiled in PaperWM.  Given this, and that it's pretty isolated to such a use-case , a helper function would also likely be pretty isolated.  

Certainly I agree though (and it woudn't hurt) - I could implement a helper function for activating windows (e.g. `Tiling.activateWindowAfterTransitions(metaWindow)` or something).  At least I could then add some function comments referencing the issue in one spot etc.).

Comment (jtaala) [reply tiling.js]: Thanks @smichel17 this one should be good to go now.  Created the function that can be reused to activate window only after transitions are complete.

**Review by smichel17 — APPROVED** [review]
I'd love if someone else would review this for the gnome-specific bits (confirming that this is the correct workaround), but otherwise the code looks good to me.

**Comment by jtaala** [comment]
> I'd love if someone else would review this for the gnome-specific bits (confirming that this is the correct workaround), but otherwise the code looks good to me.

Thanks @smichel17, I've been digging into this issue (on the gnome side) a bit more.  You'll note that I've changed the signal to `show`.  Now `transitions-completed` signal did work - but it did throw an exception in the logs re the floating windows' workspace being null - which I posit is due to `transitions-completed` being emitted before the window is rendered (and the workspace property added).

In any case, the `show` signal does not exhibit any errors/exceptions in the log.  The `show` signal is emitted once the actor is fully visible and rendered on the stage.

As for the "correct" workaround - I believe this is it - or at least it's the only known workaround thus far.  Given this, and that it "fixes" (or works around) a pretty severe gnome crashing bug - I say we implement this and if a better one is found in the future we can change it then.

Given that this method is only used for windows on the scratch layer (and simply calls `activate` after it's rendered) - I see there is little chance with causing other issues.

**Comment by smichel17** [comment]
That's enough of an explanation to satisfy me :)
