### PR TITLE
GNOME 48 support

### LINKED ISSUE #1002: GNOME 48 support
**Describe the bug**
Many keyboard shortcuts stop working in Gnome 48. (Specifically, "window left" and "window right").

**To Reproduce**
1. Open two windows.
2. Hit `Windows+Right arrow`.
3. Observe an error on the gnome shell console and no window movement.

```
Mär 06 15:25:41 arc gnome-shell[3019]: JS ERROR: TypeError: binding.is_reversed is not a function
                                        preview_navigate@file:///home/andreas/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/navigator.js:549:27
                                        asKeyHandler/<@file:///home/andreas/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/keybindings.js:368:51
                                        @resource:///org/gnome/shell/ui/init.js:21:20
```

**System information:**

```
Distribution: Debian GNU/Linux
GNOME Shell: 48.rc
Display server: Wayland
PaperWM version: 47.1.0
Enabled extensions:
- appindicatorsupport@rgcjonas.gmail.com
- caffeine@patapon.info
- switcher@landau.fi
- paperwm@paperwm.github.com
- native-window-placement@gnome-shell-extensions.gcampax.github.com
- windowsNavigator@gnome-shell-extensions.gcampax.github.com
```

### PR DESCRIPTION
**Pull request by Thesola10**
This fixes #1002 by restoring PaperWM functionality on the latest GNOME 48.

Contributions are welcome!

### CODE REVIEW

**Comment by mehiel** [comment]
Tried this branch after setting metadata.json to support 48 version but unfortunately when I activate the extension breaks gnome which exists the current sessions and goes back to gdm to login.

**Comment by Plyply99** [comment]
> Tried this branch after setting metadata.json to support 48 version but unfortunately when I activate the extension breaks gnome which exists the current sessions and goes back to gdm to login.

I experienced exact same thing.

**Comment by Thesola10** [comment]
There are no changes yet, just a setup for GNOME 48 testing, hence the "contributions are welcome".
Also yeah I forgot to bump metadata.json

**Comment by amfern** [comment]
I get a crash when trying to use this branch.
[journal-paperwm.log](https://github.com/user-attachments/files/19401438/journal-paperwm.log)

**Comment by amfern** [comment]
[96ae4ebf-5028-4dce-a82c-bd076da20b03.log](https://github.com/user-attachments/files/19403302/96ae4ebf-5028-4dce-a82c-bd076da20b03.log)
gdb back trace

**Comment by azmeuk** [comment]
No crash for me, but navigation shortcuts are broken.

**Comment by schrieveslaach** [comment]
> No crash for me, but navigation shortcuts are broken.

Same on my machine

**Comment by Thesola10** [comment]
@schrieveslaach @azmeuk just pushed a fix for navigation keybinds

**Comment by azmeuk** [comment]
> @schrieveslaach @azmeuk just pushed a fix for navigation keybinds

I confirm this fixes the issues for me.

**Comment by fermuch** [comment]
> @schrieveslaach @azmeuk just pushed a fix for navigation keybinds

I can confirm it is working for me too. Thanks!

File: topbar.js [hunk 1]
```diff
@@ -72,9 +72,10 @@ export function enable (extension) {
     Main.panel.addToStatusArea('FocusButton', focusButton, 2, 'left');
     Main.panel.addToStatusArea('OpenPositionButton', openPositionButton, 3, 'left');
 
+    /* This causes a crash on GNOME 48
     Tiling.spaces.forEach(s => {
         s.workspaceLabel.clutter_text.set_font_description(menu.label.clutter_text.font_description);
-    });
+    });*/
```
Comment (Thesola10) [inline topbar.js:78]: Need to investigate effects on GNOME 47, most likely cosmetic.

**Comment by thenameisluk** [comment]
just wanted to let you know
that dragging window using titlebar
is instantly crashing shell
```
Distribution: Debian GNU/Linux
GNOME Shell: 48.0
Display server: Wayland
PaperWM version: 48.0.0
Enabled extensions:
- gravatar@dsheeler.net
- gnomebedtime@ionutbortis.gmail.com
- caffeine@patapon.info
- weatheroclock@CleoMenezesJr.github.io
- custom-command-toggle@storageb.github.com
- ddterm@amezin.github.com
```
(on this branch)

**Comment by Thesola10** [comment]
@thenameisluk It seems to be an [upstream issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/3960) somehow??? Apparently they [merged a fix](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4307) a few days ago

In the mean time you can disable cursor change by removing line 69 from `grab.js`, might block cursor change if version=48.0
```js
        global.display.set_cursor(Meta.Cursor.MOVE_OR_RESIZE_WINDOW);
```

**Comment by schrieveslaach** [comment]
> @schrieveslaach @azmeuk just pushed a fix for navigation keybinds

Super + . and other keybindings work again.

**Comment by thenameisluk** [comment]
this only postponed the crash
it will work if you just grab it
but moving it down will again result in a crash

**Comment by data-flux** [comment]
Fedora Silverblue 42 beta, gnome version 48rc
- Keyboard navigation works perfectly!
- moving tiled windows with the mouse still crashes.

**Comment by Thesola10** [comment]
Nevermind, found it: for some reason `Meta.Cursor.MOVE_OR_RESIZE_WINDOW` is undefined on GNOME 48, and of course Clutter responds by imploding on the spot.

~~Sure, GNOME, why don't you rename the cursors without a release note, and not bother handling the old names. Gotta love Javascript.~~

File: topbar.js (hunk 1 above)
Comment (Thesola10) [reply topbar.js:78]: Yep, seems unnecessary on modern GNOME.

**Comment by thenameisluk** [comment]
this fixed the crash
thx

File: topbar.js (hunk 1 above)
Comment (jtaala) [reply topbar.js:78]: Indeed, likely from previous gnome versions.  Have tested on 47 and doesn't look like needed (or at least couldn't notice any issues here).

**Review by jtaala — APPROVED** [review]
Nice work @Thesola10!

Now running this - working well.  Happy for this to be merged when you're ready.

**Comment by jtaala** [comment]
@Thesola10, let me know if you're waiting on anything, otherwise I can merge and create a new release (on EGO as well).

Jay.

**Comment by Thesola10** [comment]
No, please go ahead, had other things to do today and forgot

**Comment by jtaala** [comment]
> No, please go ahead, had other things to do today and forgot

No problems!
